# This workflow will apply the corresponding label on a pull request
name: PR Labeler

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ github.token }}
